language: c

env:
 - SHELL=sh
 - SHELL=zsh
 - SHELL=ksh

addons:
  apt:
    packages: [zsh, ksh]


script: "$SHELL ./travis.sh"

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages: [shellcheck, binutils-dev, libcurl4-openssl-dev, zlib1g-dev, libdw-dev, libiberty-dev]
      install:
        - KCOV_VERSION=34
        - curl -fsSL https://github.com/SimonKagstrom/kcov/archive/v"$KCOV_VERSION".tar.gz | tar -C "$HOME" -zxf -
        - pushd "$HOME/kcov-$KCOV_VERSION"
        - cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local .
        - make install -j$(nproc)
        - popd
      script: kcov --exclude-pattern=travis.sh $PWD/coverage ./travis.sh
      after_success: bash <(curl -s https://codecov.io/bash) -s $PWD/coverage
    - os: osx
      script: ./travis.sh
